### Data Engineering 
#### Numpy (Creating Array)

In [1]:
import numpy as np

In [31]:
l1=[1,2,3]

In [32]:
array1=np.array(l1)

In [33]:
array1

array([1, 2, 3])

In [34]:
l2=[11,22,33]
l2

[11, 22, 33]

In [35]:
l=[l1,l2]
l

[[1, 2, 3], [11, 22, 33]]

In [36]:
array_2D=np.array(l)

In [37]:
array_2D

array([[ 1,  2,  3],
       [11, 22, 33]])

In [38]:
array_2D.shape

(2, 3)

In [39]:
array_2D.dtype

dtype('int32')

In [40]:
np.zeros(3,'int')

array([0, 0, 0])

In [41]:
np.ones(3)

array([1., 1., 1.])

In [42]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros(3)
np.empty(3)

array([0., 0., 0.])

In [47]:
np.ones(3,'int')

array([1, 1, 1])

In [48]:
np.ones([3,3],'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])