### Data Engineering 
#### Numpy (Creating Array)


# Scalar Operations:

#### 1- create a 2*2 Numpy array and multiply it by 2.

In [21]:
import numpy as np

In [22]:
l1=[1,2]
l2=[3,4]
array1=np.array(l1)
array2=np.array(l2)
l=[l1,l2]
l
array_2D=np.array(l)
array_2D
array_multi=array_2D*2
array_multi

array([[2, 4],
       [6, 8]])

#### 2- create a 3*3 Numpy array and add 5 to each element.

In [23]:
l1=[1,2]
l2=[3,4]
l3=[5,6]
array1=np.array(l1)
array2=np.array(l2)
array3=np.array(l3)
l=[l1,l2,l3]
l
array=np.array(l)
array
array_add=array+5
array_add

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

#### 3- create a 4*4 Numpy array and subtract 10 from each element.

In [24]:
array=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]])
result=array-10
result

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

#### 4- create a 5*5 Numpy array and divide each element by 2.

In [25]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[16,17,18,19,20]])
result=(array/2)
print(result)

[[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [ 8.   8.5  9.   9.5 10. ]]


#### 5- create a 6*6 Numpy array and calculate the square root of each element.

In [26]:
array=np.array([[1,2,3,4,5,6],[6,7,8,9,10,25],[11,12,13,14,15,45],[16,17,18,19,20,60],[20,60,49,35,12,21],[6,14,8,9,10,25]])
result=(array**0.5)
print(result)

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766 5.        ]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 6.70820393]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595 7.74596669]
 [4.47213595 7.74596669 7.         5.91607978 3.46410162 4.58257569]
 [2.44948974 3.74165739 2.82842712 3.         3.16227766 5.        ]]


# Matrix Product and Multiplication:

#### 6. Create two 2x2 NumPy arrays and calculate their product using the np.matmul() function

In [32]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
product=np.matmul(array1,array2)
print(product)


[[19 22]
 [43 50]]


#### 7. Create two 3x3 NumPy arrays and calculate their product using the np.dot() function.

In [34]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

product = np.dot(arr1, arr2)

print(product)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


#### 8. Create a 2x3 NumPy array and a 3x2 NumPy array, and calculate their product using the np.matmul() function.



In [37]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print('The array1 is:\n',array1)
array2 = np.array([[7, 8], [9, 10], [11, 12]])
print('\nThe array2 is:\n',array2)

product = np.matmul(array1, array2)
print('\nThe product of array1 and array2 is:\n',product)

The array1 is:
 [[1 2 3]
 [4 5 6]]

The array2 is:
 [[ 7  8]
 [ 9 10]
 [11 12]]

The product of array1 and array2 is:
 [[ 58  64]
 [139 154]]


#### 9. Create a 3x2 NumPy array and a 2x3 NumPy array, and calculate their product using the np.dot() function.


In [39]:
array1=np.array([[1,2,3],[4,5,6]])
print('The array1 is:\n',array1)
array2 = np.array([[7, 8], [9, 10], [11, 12]])
print('\nThe array2 is:\n',array2)

product = np.dot(array1, array2)
print('\nThe product of array1 and array2 is:\n',product)


The array1 is:
 [[1 2 3]
 [4 5 6]]

The array2 is:
 [[ 7  8]
 [ 9 10]
 [11 12]]

The product of array1 and array2 is:
 [[ 58  64]
 [139 154]]


#### 10. Create a 4x4 NumPy array and its transpose using the np.transpose() function, then calculate their product using the np.matmul() function.

In [44]:
array=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print('The array1 is:\n',array)

transpose = np.transpose(array)
print('\nThe array1 is:\n',transpose)

product = np.matmul(array, transpose)
print('\nThe product of array and transpose is:\n',product)

The array1 is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The array1 is:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

The product of array and transpose is:
 [[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]


# Transpose:


#### 11. Create a 2x3 NumPy array and its transpose using the np.transpose() function.


In [67]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print('The  array is:\n',array)

transpose = np.transpose(array)
print('\nThe transpose of the array is:\n',transpose)


The  array is:
 [[1 2 3]
 [4 5 6]]

The transpose of the array is:
 [[1 4]
 [2 5]
 [3 6]]


#### 12. Create a 3x4 NumPy array and its transpose using the np.transpose() function.


In [68]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('The  array is:\n',array)

transpoe=np.transpose(array)
print('\nThe transpose of the array is:\n',transpoe)

The  array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The transpose of the array is:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### 13. Create a 5x5 NumPy array and its transpose using the np.transpose() function.


In [69]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print('The  array is:\n\n',array)

transpose=np.transpose(array)
print('\nThe transpose of the array is:\n\n',transpose)

The  array is:

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

The transpose of the array is:

 [[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


#### 14. Create a 2x2 NumPy array and its transpose using the np.transpose() function, then calculate the dot product of the two arrays using the np.dot() function.

In [63]:
array = np.array([[1, 2], [3, 4]])
print('The  array is:\n\n',array)

transpose=np.transpose(array)
print('\nThe transpose of the array is:\n\n',transpose)

dot_product = np.dot(array, transpose)
print('\nThe dot product of the array and transpose is:\n\n',dot_product)

The  array is:

 [[1 2]
 [3 4]]

The transpose of the array is:

 [[1 3]
 [2 4]]

The dot product of the array and transpose is:

 [[ 5 11]
 [11 25]]


# Dot Product:


#### 15. Create two 2x2 NumPy arrays and calculate their dot product using the np.dot() function.


In [73]:
array1= np.array([[1, 2], [3, 4]])
print('The  array1 is:\n\n',array1)

array2= np.array([[5,6], [7,8]])
print('The  array2 is:\n\n',array2)

dot_product = np.dot(array1, array2)
print('\nThe dot product of the array1 and array2 is:\n\n',dot_product)

The  array1 is:

 [[1 2]
 [3 4]]
The  array2 is:

 [[5 6]
 [7 8]]

The dot product of the array1 and array2 is:

 [[19 22]
 [43 50]]


#### 16. Create two 3x3 NumPy arrays and calculate their dot product using the np.dot() function.


In [74]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('The  array1 is:\n\n',array1)

array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print('The  array2 is:\n\n',array2)

dot_product = np.dot(array1, array2)
print('\nThe dot product of the array1 and array2 is:\n\n',dot_product)

The  array1 is:

 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The  array2 is:

 [[10 11 12]
 [13 14 15]
 [16 17 18]]

The dot product of the array1 and array2 is:

 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


#### 17. Create a 2x3 NumPy array and a 3x2 NumPy array, and calculate their dot product using the np.dot() function.


In [75]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print('The  array1 is:\n\n',array1)

array2 = np.array([[7, 8], [9, 10], [11, 12]])
print('The  array2 is:\n\n',array2)

dot_product = np.dot(array1, array2)
print('\nThe dot product of the array1 and array2 is:\n\n',dot_product)

The  array1 is:

 [[1 2 3]
 [4 5 6]]
The  array2 is:

 [[ 7  8]
 [ 9 10]
 [11 12]]

The dot product of the array1 and array2 is:

 [[ 58  64]
 [139 154]]


#### 18. Create a 3x2 NumPy array and a 2x3 NumPy array, and calculate their dot product using the np.dot() function.


In [76]:
array1 = np.array([[7, 8], [9, 10], [11, 12]])
print('The  array1 is:\n\n',array1)

array2 =np.array([[1, 2, 3], [4, 5, 6]])   
print('The  array2 is:\n\n',array2)

dot_product = np.dot(array1, array2)
print('\nThe dot product of the array1 and array2 is:\n\n',dot_product)

The  array1 is:

 [[ 7  8]
 [ 9 10]
 [11 12]]
The  array2 is:

 [[1 2 3]
 [4 5 6]]

The dot product of the array1 and array2 is:

 [[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


#### 19. Create a 4x4 NumPy array and its transpose using the np.transpose() function, then calculate their dot product using the np.dot() function.


In [77]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print('The  array is:\n\n',array)


transpose = np.transpose(array)
print('\nThe transpose of the array is:\n\n',transpose)

dot_product = np.dot(array, transpose)
print('\nThe dot product of the array and transpose is:\n\n',dot_product)



The  array is:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The transpose of the array is:

 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

The dot product of the array and transpose is:

 [[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]


#### 20. Create a 5x5 NumPy array and its inverse using the np.linalg.inv() function, then calculate the dot product of the array and its inverse using the np.dot() function.

In [80]:
array = np.random.randint(1, 10, (5, 5))
print('The array is:\n',array)

inverse = np.linalg.inv(array)
print('\nThe array is:\n',inverse)


dot_product = np.dot(array, inverse)
print('\nThe dot product of array is:\n',dot_product)

The array is:
 [[4 4 5 8 2]
 [1 7 5 9 1]
 [5 2 4 2 2]
 [9 2 8 6 3]
 [7 7 1 6 6]]

The array is:
 [[-7.06329114  3.11392405 -7.02531646  5.82278481  1.26582278]
 [-3.17721519  1.51898734 -2.67088608  2.30379747  0.5443038 ]
 [ 4.84810127 -2.12658228  5.13924051 -4.02531646 -0.96202532]
 [-0.75949367  0.36708861 -1.30379747  0.87341772  0.18987342]
 [11.89873418 -5.41772152 11.75949367 -9.6835443  -1.97468354]]

The dot product of array is:
 [[ 1.00000000e+00 -1.77635684e-15  0.00000000e+00  0.00000000e+00
  -8.88178420e-16]
 [ 1.77635684e-15  1.00000000e+00  1.77635684e-15  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00 -1.77635684e-15  1.00000000e+00  3.55271368e-15
  -1.33226763e-15]
 [-1.77635684e-15  0.00000000e+00 -5.32907052e-15  1.00000000e+00
  -3.10862447e-15]
 [-3.55271368e-15  0.00000000e+00 -1.06581410e-14  1.42108547e-14
   1.00000000e+00]]
