### Data Engineering 
#### Numpy (Array Indexing)


#### 1. Create a 1D NumPy array with the integers from 0 to 9. Extract the 3rd element from the array

In [1]:
import numpy as np

In [4]:
arr=np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[2]

2

#### 2. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Extract the element at row 2, column 1.

In [7]:
arr=np.random.rand(3,3)
arr

array([[0.50654318, 0.61354688, 0.37701314],
       [0.21370404, 0.98085188, 0.53098756],
       [0.69876956, 0.09280342, 0.69412318]])

In [9]:
arr[1][0]

0.2137040449424641

#### 3. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarray consisting of the first 2 rows and the last 2 columns.

In [10]:
arr=np.random.rand(4,4) 
arr

array([[0.41447342, 0.22216465, 0.87608975, 0.22332433],
       [0.44886536, 0.89227939, 0.82745815, 0.24977603],
       [0.1110191 , 0.91313488, 0.15099368, 0.10060302],
       [0.6477815 , 0.32527211, 0.94664289, 0.98026859]])

In [11]:
arr[:2,-2:]

array([[0.87608975, 0.22332433],
       [0.82745815, 0.24977603]])

#### 4. Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the first 3 elements.


In [12]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
slice_of_arr=arr[:3]
slice_of_arr

array([0, 1, 2])

#### 5. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the array consisting of the first 2 rows and the first 2 columns.


In [14]:
arr=np.random.rand(3,3)
arr

array([[0.28443733, 0.9975041 , 0.60632495],
       [0.77578965, 0.92009568, 0.00311121],
       [0.65323454, 0.68304572, 0.11625367]])

In [15]:
arr[:2,:2]

array([[0.28443733, 0.9975041 ],
       [0.77578965, 0.92009568]])

#### 6. Create a 1D NumPy array with the integers from 0 to 8. Reshape the array into a 2D array with shape (3, 3).

In [38]:
arr=np.arange(0,9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array into a 1D array.

In [55]:
arr=np.random.rand(4,4)
print('original array:', arr)

print('\nreshaped array:',arr.flatten())

original array: [[0.58916716 0.1780314  0.43883646 0.62153094]
 [0.10118185 0.72674249 0.09637065 0.71682335]
 [0.79561381 0.97596871 0.43849254 0.38370948]
 [0.56993066 0.12164688 0.90304083 0.8883124 ]]

reshaped array: [0.58916716 0.1780314  0.43883646 0.62153094 0.10118185 0.72674249
 0.09637065 0.71682335 0.79561381 0.97596871 0.43849254 0.38370948
 0.56993066 0.12164688 0.90304083 0.8883124 ]


#### 8. Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into a single 1D array.


In [65]:
arr1=np.arange(0,5)
print('array 1:',arr1)
arr2=np.arange(0,5)
print('\narray 2:',arr2)   
print('The concatenated array: ',np.concatenate([arr1,arr2]))



array 1: [0 1 2 3 4]

array 2: [0 1 2 3 4]
The concatenated array:  [0 1 2 3 4 0 1 2 3 4]


#### 9. Create two 2D NumPy arrays with shapes (2, 2) and (2, 3). Concatenate the two arrays horizontally.

In [75]:
arr1=np.random.rand(2,2)
print('array 1:\n', arr1)

arr2=np.random.rand(2,3)
print('\narray 2:\n', arr2)

print('\nThe concatenated array: \n',np.hstack([arr1,arr2]))  #hstack() function to concatenate the two arrays horizontally. 


array 1:
 [[0.12285146 0.06888725]
 [0.32554743 0.47028748]]

array 2:
 [[0.09576736 0.00171285 0.08357784]
 [0.09976082 0.19284866 0.46613728]]

The concatenated array: 
 [[0.12285146 0.06888725 0.09576736 0.00171285 0.08357784]
 [0.32554743 0.47028748 0.09976082 0.19284866 0.46613728]]


#### 10. Create two 2D NumPy arrays with shapes (2, 2) and (3, 2). Concatenate the two arrays vertically.


In [78]:
arr1=np.random.rand(2,2)
print('array 1:\n', arr1)

arr2=np.random.rand(3,2)
print('\narray 2:\n', arr2)

print('\nThe concatenated array: \n',np.vstack([arr1,arr2]))  #vstack() function to concatenate the two arrays vertically. 

array 1:
 [[0.63236931 0.46588268]
 [0.84868958 0.60510799]]

array 2:
 [[0.98837046 0.17179563]
 [0.86042658 0.8598154 ]
 [0.4117696  0.37757446]]

The concatenated array: 
 [[0.63236931 0.46588268]
 [0.84868958 0.60510799]
 [0.98837046 0.17179563]
 [0.86042658 0.8598154 ]
 [0.4117696  0.37757446]]


#### 11. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Split the array into two equal horizontal halves.


In [88]:
array =np.random.rand(4,4)
print('The original array :\n', array)

upper,lower=np.vsplit(array,[2])
print('\nThe splitted array :')
print('\nThe upper array\n',upper)
print('\nThe lower array\n',lower)


The original array :
 [[0.76869082 0.34333345 0.33229252 0.30578808]
 [0.73857658 0.52036545 0.03027007 0.85984353]
 [0.51377728 0.0826623  0.38045116 0.46159507]
 [0.92939926 0.56524012 0.04106212 0.50697463]]

The splitted array :

The upper array
 [[0.76869082 0.34333345 0.33229252 0.30578808]
 [0.73857658 0.52036545 0.03027007 0.85984353]]

The lower array
 [[0.51377728 0.0826623  0.38045116 0.46159507]
 [0.92939926 0.56524012 0.04106212 0.50697463]]


#### 12. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Split the array into two equal vertical halves.

In [89]:
array =np.random.rand(4,4)
print('The original array :\n', array)

upper,lower=np.hsplit(array,[2])
print('\nThe splitted array :')
print('\nThe upper array\n',upper)
print('\nThe lower array\n',lower)

The original array :
 [[0.60796204 0.57434318 0.34006201 0.82832099]
 [0.63645827 0.52733641 0.83420678 0.97091653]
 [0.689332   0.00362323 0.42727401 0.72344068]
 [0.32846396 0.69882146 0.17639846 0.40644522]]

The splitted array :

The upper array
 [[0.60796204 0.57434318]
 [0.63645827 0.52733641]
 [0.689332   0.00362323]
 [0.32846396 0.69882146]]

The lower array
 [[0.34006201 0.82832099]
 [0.83420678 0.97091653]
 [0.42727401 0.72344068]
 [0.17639846 0.40644522]]


#### 13. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Split the array into four equal subarrays.

In [102]:
array =np.random.rand(4,4)
print('The original array :\n', array)

a,b,c,d=np.split(array,4,axis=0) # split horizontally
#a,b,c,d=np.split(array,4,axis=1) # split vertically
print('\nThe splitted array :')
print('\nThe first subarray\n',a)
print('\nThe second subarray\n',b)
print('\nThe third subarray\n',c)
print('\nThe fourth subarray\n',d)


The original array :
 [[0.08581389 0.34806697 0.70129404 0.96731684]
 [0.05375226 0.95753066 0.57772125 0.22088043]
 [0.94685545 0.87226304 0.72750362 0.76072896]
 [0.48198819 0.97539752 0.5636817  0.74101867]]

The splitted array :

The first subarray
 [[0.08581389 0.34806697 0.70129404 0.96731684]]

The second subarray
 [[0.05375226 0.95753066 0.57772125 0.22088043]]

The third subarray
 [[0.94685545 0.87226304 0.72750362 0.76072896]]

The fourth subarray
 [[0.48198819 0.97539752 0.5636817  0.74101867]]


#### 14. Create a 1D NumPy array with the integers from 0 to 9. Set all odd elements of the array to zero using array indexing.

In [112]:
array=np.arange(0,10)
print('The oroginal array\n',array)

array[array % 2 == 1] = 0
print('\nThe edited array is:\n',array)

The oroginal array
 [0 1 2 3 4 5 6 7 8 9]

The edited array is:
 [0 0 2 0 4 0 6 0 8 0]


#### 15. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Set all elements of the first row to zero using array indexing.

In [117]:
array = np.random.randint(0, 10, (3, 3))
print('The oroginal array\n',array)
array[0] = 0
print('\nThe edited array is:\n',array)

The oroginal array
 [[2 1 8]
 [7 6 3]
 [5 7 4]]

The edited array is:
 [[0 0 0]
 [7 6 3]
 [5 7 4]]


#### 16. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Set all elements of the last column to zero using array indexing.

In [119]:
array = np.random.randint(0, 10, (3, 3))
print('The oroginal array\n',array)
array[2] = 0
print('\nThe edited array is:\n',array)

The oroginal array
 [[8 7 2]
 [2 1 8]
 [6 9 3]]

The edited array is:
 [[8 7 2]
 [2 1 8]
 [0 0 0]]


#### 17. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Set all elements in the subarray consisting of the first 2 rows and the last 2 columns to zero using array indexing.

In [149]:
array = np.random.randint(0, 10, (3, 3))
print('The oroginal array\n',array)

array[:2, 1:] = 0
print('The subarray\n',array)



The oroginal array
 [[6 0 8]
 [7 1 9]
 [6 3 1]]
The subarray
 [[6 0 0]
 [7 0 0]
 [6 3 1]]


#### 18. Create a 1D NumPy array with the integers from 0 to 9. Copy the entire array and modify the copy so that all elements are multiplied by 2.

In [124]:
array=np.arange(0,10)
print('The oroginal array:\n',array)

copy=array.copy()
print('\nThe copy of the array:\n',copy)

copy= copy*2
print('\nThe copy of the array after multiplied by 2:\n',copy)


The oroginal array:
 [0 1 2 3 4 5 6 7 8 9]

The copy of the array:
 [0 1 2 3 4 5 6 7 8 9]

The copy of the array after multiplied by 2:
 [ 0  2  4  6  8 10 12 14 16 18]


#### 19. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy the entire array and modify the copy so that all elements are added by 1.


In [126]:
array = np.random.randint(0, 10, (3, 3))
print('The oroginal array:\n',array)

copy=array.copy()
print('\nThe copy of the array:\n',copy)

copy= copy+1
print('\nThe copy of the array after added by 1:\n',copy)

The oroginal array:
 [[0 1 6]
 [3 6 1]
 [6 4 3]]

The copy of the array:
 [[0 1 6]
 [3 6 1]
 [6 4 3]]

The copy of the array after added by 1:
 [[1 2 7]
 [4 7 2]
 [7 5 4]]


#### 20. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the array consisting of the first 2 rows and the first 2 columns, and modify the copy so that all

In [133]:
array=np.random.randint(0,10,(3,3))
print('The oroginal array:\n',array)

slice = array[:2, :2]
print('\nThe slice of array:\n',slice)


The oroginal array:
 [[1 3 3]
 [9 0 7]
 [6 3 1]]

The slice of array:
 [[1 3]
 [9 0]]
