### Data Engineering 
#### Numpy (Universal Array Function) 

#### 1. Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp() function to compute the exponential of each element in the array.

In [1]:
import numpy as np

In [27]:
array=np.random.rand(3,3)
print('The original array:\n',array)

a=np.exp(array)
print('\nThe exponential of each element in array:\n',a)


The original array:
 [[0.47241822 0.00330225 0.53439254]
 [0.09557252 0.96653155 0.21402091]
 [0.58287502 0.91757059 0.52901808]]

The exponential of each element in array:
 [[1.60386801 1.00330771 1.70641135]
 [1.10028862 2.62881074 1.23864856]
 [1.79118072 2.50320168 1.69726491]]


#### 2.Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function to compute the sine of each element in the array.


In [28]:
array=np.random.rand(4,4)
print('The original array:\n',array)

sine_array=np.sin(array)
print('\nThe sine of each element in the array:\n',sine_array)


The original array:
 [[0.21696662 0.62459469 0.45295462 0.28247207]
 [0.33354298 0.07993825 0.08585117 0.74836616]
 [0.31196009 0.89308964 0.03012952 0.75010166]
 [0.60784287 0.98946942 0.84956625 0.3526651 ]]

The sine of each element in the array:
 [[0.21526835 0.58476853 0.43762411 0.2787306 ]
 [0.3273928  0.07985314 0.08574574 0.68044239]
 [0.30692471 0.77901269 0.03012497 0.68171314]
 [0.57109804 0.83573474 0.75099407 0.34540011]]


#### 3. Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log() function to compute the natural logarithm of each element in the array.

In [67]:
arr=np.random.rand(5,5)
print('The original array:\n',arr)

arr_log=np.log(arr_exp)
print('\n The natural logarithm:\n',arr)



The original array:
 [[0.60624174 0.08947611 0.87943839 0.2519195  0.60089327]
 [0.0414102  0.5337825  0.63430608 0.92711042 0.9108766 ]
 [0.12790356 0.92533879 0.30678021 0.40995006 0.55782432]
 [0.1275603  0.81117835 0.19399544 0.69194801 0.0439449 ]
 [0.0026755  0.61619634 0.48761229 0.88268193 0.13986289]]

 The natural logarithm:
 [[0.60624174 0.08947611 0.87943839 0.2519195  0.60089327]
 [0.0414102  0.5337825  0.63430608 0.92711042 0.9108766 ]
 [0.12790356 0.92533879 0.30678021 0.40995006 0.55782432]
 [0.1275603  0.81117835 0.19399544 0.69194801 0.0439449 ]
 [0.0026755  0.61619634 0.48761229 0.88268193 0.13986289]]


#### 4. Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt() function to compute the square root of each element in the array.

In [31]:
arr=np.random.rand(2,2)
print('The original array:\n',arr)

arr_sqrt=np.sqrt(arr)
print('\nThe square root of each element in the array:\n',arr_sqrt)

The original array:
 [[0.07962222 0.57874546]
 [0.20092755 0.67614948]]

The square root of each element in the array:
 [[0.2821741  0.76075322]
 [0.44824943 0.82228309]]


#### 5. Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor() function to round down each element in the array to the nearest integer.

In [48]:
arr=np.random.rand(6,6)
print('The original array:\n',arr)

arr_floor=np.floor(arr)
print('\nThe rounded array:\n',arr_floor)

The original array:
 [[0.92277858 0.82354433 0.88273944 0.47282854 0.0464822  0.88313683]
 [0.87917438 0.27311654 0.91288069 0.08065842 0.5746857  0.80622921]
 [0.78203705 0.80336941 0.75346296 0.96349702 0.13526393 0.70331957]
 [0.78090878 0.89747519 0.02003188 0.93723284 0.23606811 0.58175284]
 [0.50574205 0.56714414 0.75081669 0.21158629 0.44631574 0.4953242 ]
 [0.64186767 0.20127969 0.47514561 0.71439469 0.86783083 0.50253531]]

The rounded array:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


####  6. Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs() function to compute the absolute value of each element in the array.


In [65]:
arr=np.random.rand(3,3)
print('The original array:\n',arr)

arr_abs=np.abs(arr)
print('\nThe absolute for array:\n',arr_abs)

#a=np.array([-1,9,-3,-19])
#print('The original array:\n',a)
#arr_abs=np.abs(a)
#print('\nThe absolute for array:\n',arr_abs)

The original array:
 [[0.8527617  0.24250445 0.95636325]
 [0.73262142 0.88058611 0.11813096]
 [0.72458104 0.55058331 0.20719878]]

The absolute for array:
 [[0.8527617  0.24250445 0.95636325]
 [0.73262142 0.88058611 0.11813096]
 [0.72458104 0.55058331 0.20719878]]


#### 7. Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power()function to raise each element in the array to the power of 2.


In [72]:
arr=np.random.rand(4,4)
print('The original array:\n',arr)

arr_power=np.power(arr,2)
print('\nThe power for array:\n',arr_power)

The original array:
 [[0.14671557 0.46274882 0.05692563 0.16286205]
 [0.14095927 0.14554119 0.19692026 0.84483712]
 [0.38277097 0.92088015 0.30934995 0.27570566]
 [0.38663943 0.19992677 0.7650183  0.00688753]]

The power for array:
 [[2.15254576e-02 2.14136466e-01 3.24052712e-03 2.65240479e-02]
 [1.98695153e-02 2.11822375e-02 3.87775903e-02 7.13749764e-01]
 [1.46513618e-01 8.48020246e-01 9.56973905e-02 7.60136083e-02]
 [1.49490048e-01 3.99707134e-02 5.85253005e-01 4.74380109e-05]]


#### 8. Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to find the largest element in the array.

In [79]:
arr=np.random.randint(1,11,5)
print('The original array:\n',arr)

arr_max=np.max(arr)
print('\nThe largest element in the array:',arr_max)

The original array:
 [10  4  4  6  6]

The largest element in the array: 10


#### 9. Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round function to round each element to the nearest integer.


In [84]:
arr=np.random.rand(10)
print('The original array:\n',arr)

arr_round=np.round(arr)
print('\n The round of each element in array:',arr_round)


The original array:
 [0.5258305  0.79883096 0.46353116 0.33162762 0.59278216 0.01279111
 0.04009042 0.2319211  0.57510518 0.40300637]

 The round of each element in array: [1. 1. 0. 0. 1. 0. 0. 0. 1. 0.]


#### 10. Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to find the index of the largest element in the array.


In [87]:
arr=np.random.randint(1,101,7)
print('The original array:\n',arr)

arr_argmax=np.argmax(arr)
print(arr_argmax)

The original array:
 [85  7 93 57 59 92 66]
2


#### 11. Create two NumPy arrays with the same shape, each filled with random integers between 1 and 10. Use the add function to add the two arrays together element-wise.


In [99]:
arr1=np.random.randint(1,11,size=(2,2))
print('The array 1:\n',arr1)

arr2=np.random.randint(1,11,size=(2,2))
print('\nThe array 2:\n',arr2)

a=np.add(arr1,arr2)
print('\n The added arrays\n',a)


The array 1:
 [[3 2]
 [2 9]]

The array 2:
 [[7 2]
 [5 8]]

 The added arrays
 [[10  4]
 [ 7 17]]


#### 12. Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit the values in the array to a range between 10 and 90.

In [106]:
arr=np.random.randint(0,101,12)
print('The original array:\n',arr)

arr_clip=np.clip(arr,10,90)
print('\nThe cliped array:\n',arr_clip)

The original array:
 [77 42 68 62  0 63 86 10 79  3 23 43]

The cliped array:
 [77 42 68 62 10 63 86 10 79 10 23 43]
