# Data Engineering 
Numpy (Array Processing)


#### 1. Create a NumPy array with 10 random integers between 0 and 100.

In [1]:
import numpy as np

In [3]:
arr=np.random.randint(0,101,10)
print('The array:',arr)

The array: [55  8 50 90 94 21 96 76 95 35]


#### 2. Use the np.where() function to create a new array with the same shape as the previous one, where values less than 50 are replaced with -1 and values greater than or equal to 50 are replaced with 1.


In [8]:
arr=np.random.randint(0,101,10)
print('The array:',arr)
print('new array:',np.where(50>arr,-1,1))


The array: [94 21 32 39 67 44  9 93 91 77]
new array: [ 1 -1 -1 -1  1 -1 -1  1  1  1]


#### 3. Calculate the mean, median, and standard deviation of the original array.

In [12]:
arr=np.random.randint(0,101,10)
print('The array:\n',arr)
m=np.mean(arr)
print('\nThe mean of the array:\n',m)
med=np.median(arr)
print('\nThe median of the array:\n',med)
s=np.std(arr)
print('\nThe standard deviation of the array:\n',s)

The array:
 [26 80  2 72 77 13 41 58  1  8]

The mean of the array:
 37.8

The median of the array:
 33.5

The standard deviation of the array:
 30.304455118018538


#### 4. Create a boolean array that is True where the values in the original array are even, and False otherwise.

In [61]:
arr=np.random.randint(0,101,10)
print('The original array:',arr)
print('The boolean array:',np.where(arr%2==0,True,False))


The original array: [67 88  6 69 19 11 18  4 49 19]
The boolean array: [False  True  True False False False  True  True False False]


#### 5. Sort the original array in ascending order.

In [62]:
arr=np.random.randint(0,101,10)
print('The original array:\n',arr)

array_sort=np.sort(arr)
print('\nThe array in ascending order:\n',array_sort)

The original array:
 [72 12 54 31 28 32 15 97 61 34]

The array in ascending order:
 [12 15 28 31 32 34 54 61 72 97]


#### 6. Find the unique values in the original array.

In [24]:
array=np.array(['Maathar','Mansoor','Ali','Maathar','Abdullah','Mohammed','Ali'])
print('The original array\n',array)

array_unique=np.unique(array)
print(array_unique)

The original array
 ['Maathar' 'Mansoor' 'Ali' 'Maathar' 'Abdullah' 'Mohammed' 'Ali']
['Abdullah' 'Ali' 'Maathar' 'Mansoor' 'Mohammed']


#### 7. Use the np.in1d() function to create a boolean array indicating which elements of the original array are also present in a new array with 5 random integers between 0 and 100.

In [51]:
arr=np.random.randint(0,101,10)
print('The original array:\n',arr)

array=np.random.randint(0,101,5)
print('\nThe new array:\n',array)

array_boolean=np.in1d(array,a)
print('\n The boolean array:\n',array_boolean)


The original array:
 [52 64 28 97  2 15 64 83 87 76]

The new array:
 [20 54 78  7 71]

 The boolean array:
 [False False False  True False]


#### 8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function.

In [59]:
arr=np.random.randint(0,101,10)
print('The original array:\n',arr)

#save the text file
a=np.savetxt('my_array.txt',arr,delimiter=',')

#load the text file
ar = np.loadtxt('my_array.txt',delimiter = ',')
print('\nThe loaded file:\n',ar)

The original array:
 [ 0 23 90 44 66 32 86 45 77 31]

The loaded file:
 [ 0. 23. 90. 44. 66. 32. 86. 45. 77. 31.]
